server:
  port: 8004
spring:
  application:
    name: local-grpc-client
grpc:
  server:
    port: 8001
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:8002'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
